name: build-on-push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from file
        id: extract_version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Update data in fxmanifest
        run: |
          sed -i "s/VERSION_IDENTIFIER/${{ steps.extract_version.outputs.version }}/g" fxmanifest.lua
          sed -i "s/REPO_NAME/${{ github.event.repository.name }}/g" fxmanifest.lua
          sed -i "s/AUTHOR_NAME/${{ github.repository_owner }}/g" fxmanifest.lua

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lua5.4

      - name: Build
        run: |
          git clone https://github.com/gt-scripts/lua_builder.git
          cd lua_builder/src
          chmod +x pre-build.sh
          ./pre-build.sh
          chmod +x build.sh
          ./build.sh ${{ github.event.repository.name }}

      - name: Generate Release
        uses: shogo82148/actions-create-release@v1
        id: release
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name:
          make_latest: true
          body: v${{ steps.extract_version.outputs.version }}
      - name: Upload artifacts
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: lua_builder/src/${{ github.event.repository.name }}.zip
