name: build-on-push

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get version from file
              id: extract_version
              run: |
                echo "version=$(cat version)" >> $GITHUB_OUTPUT

            - name: Build
              run: |
                git clone https://github.com/gt-scripts/lua_builder.git
                chmod +x pre-build.sh
                pre-build.sh
                chmod +x build.sh
                build.sh

            - name: Generate Release
              uses: shogo82148/actions-create-release@v1
              id: release
              with:
                tag_name: v${{ steps.extract_version.outputs.version }}
                release_name:
                make_latest: true
                body: v${{ steps.extract_version.outputs.version }}
            - name: Upload artifacts
              uses: shogo82148/actions-upload-release-asset@v1
              with:
                upload_url: ${{ steps.release.outputs.upload_url }}
                asset_path: release/${{ github.event.repository.name }}.zip